services:
  api:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: sentiment-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8000

  celery:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: sentiment-celery
    depends_on:
      - redis
    env_file:
      - .env
    command: >
      celery -A src.celery_app.celery_app
      worker --pool=solo --loglevel=info

  redis:
    image: redis:7
    container_name: sentiment-redis
    ports:
      - "6381:6381"
    command: redis-server --port 6381
